spring:
  data:
    mongodb:
      uri: 'mongodb+srv://admin:NeQqQY9LH4HagxhU@shopcluster.fdnshxy.mongodb.net/?retryWrites=true&w=majority'
      database: teamchopdb

jwt:
  secret: "secretkeyforcoinkeeperaplicatio"