spring:
  data:
    mongodb:
      uri: 'mongodb+srv://admin:NeQqQY9LH4HagxhU@shopcluster.fdnshxy.mongodb.net/?retryWrites=true&w=majority'
      database: teamshopdb


jwt:
  secret: "secretkeyforcoinkeeperaplicatio"
mongock:
  change-logs-scan-package: team.challenge.MobileStore.db.migration