spring:
  data:
    mongodb:
      uri: ${MONGO_CLOUD_URI}
      database: ${MONGO_CLOUD_DATABASE}


jwt:
  secret: "secretkeyforcoinkeeperaplicatio"
mongock:
  change-logs-scan-package: team.challenge.MobileStore.db.migration